/** Deterministic browser-test configuration, overriding local .env files. */
export const E2E_BUILD_ENV = {
  NEXT_PUBLIC_PRIVY_APP_ID: '',
  NEXT_PUBLIC_ALCHEMY_ETHEREUM_RPC_URL: '',
  NEXT_PUBLIC_ALCHEMY_BASE_RPC_URL: '',
  NEXT_PUBLIC_ALCHEMY_DATA_API_KEY: '',
  NEXT_PUBLIC_FX_SCREENSHOT_MODE: '',
  NEXT_PUBLIC_FX_SCREENSHOT_WALLET_ADDRESS: '',
  NEXT_PUBLIC_FX_ANVIL_RPC_URL: '',
  NEXT_PUBLIC_FX_LOCAL_FORK_TEST_MODE: '',
  NEXT_PUBLIC_FX_LOCAL_FORK_RPC_URL: '',
  NEXT_PUBLIC_TELEGRAM_APP_URL: 'https://t.me/FxAeonBot',
};
