#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

# Recovery from the 2026-06-11 deploy-db incident:
# 1. `20260610_init` was corrupt — a Prisma update banner had been appended
#    into migration.sql (it was generated by piping CLI output to a file), so
#    the migration died on a syntax error and rolled back: prod has NO schema.
# 2. A first recovery attempt baselined init with `migrate resolve --applied`,
#    which was wrong (the tables don't exist). That bookkeeping row must be
#    removed so the now-fixed init SQL actually runs.
#
# The DELETE below is guarded: it only removes the init row while the schema
# is demonstrably absent (no TxRecord table). Once init has truly applied,
# this is a permanent no-op — safe to keep in every deploy.
npx prisma db execute --url "$DATABASE_URL" --stdin <<'SQL'
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables
             WHERE table_schema = 'public' AND table_name = '_prisma_migrations') THEN
    -- While the schema is provably absent, drop the wrongly-"applied" init row.
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables
                   WHERE table_schema = 'public' AND table_name = 'TxRecord') THEN
      DELETE FROM "_prisma_migrations" WHERE migration_name = '20260610_init';
    END IF;
    -- Clear FAILED rows (started but never finished, not marked rolled back):
    -- the idempotent equivalent of `prisma migrate resolve --rolled-back` for
    -- every stuck migration. On Postgres each migration runs in a transaction,
    -- so a failed migration left no partial schema behind and is safe to
    -- re-apply. No-op when there are no failed rows.
    DELETE FROM "_prisma_migrations"
      WHERE finished_at IS NULL AND rolled_back_at IS NULL;
  END IF;
END $$;
SQL

# Apply pending migrations (additive-only per docs/PLAN.md policy).
npx prisma migrate deploy

# Drift visibility: if the live DB disagrees with schema.prisma, print the
# diff loudly but do not fail the deploy — drift is investigated, never
# auto-"fixed", in a production database.
npx prisma migrate diff \
  --from-url "$DATABASE_URL" \
  --to-schema-datamodel prisma/schema.prisma \
  --exit-code || echo "::warning::schema drift detected between DB and schema.prisma (see diff above)"
